spring:
  application:
    name: recipe-book-spring
de:
  flapdoodle:
    mongodb:
      embedded:
        version: "7.0.12"
app:
  cors:
    mappingPathPattern: "/**"
    allowed-origins: ${ALLOWED_SOURCES}
    allowed-methods: [ GET, POST, PUT, DELETE, PATCH ]
    allowed-headers: [ "*" ]
  key-pair:
    private-key: ${PRIVATE_KEY}
    public-key: ${PUBLIC_KEY}