spring:
  security:
    user:
      name: user
      password: password
  application:
    name: recipe-book-spring
de:
  flapdoodle:
    mongodb:
      embedded:
        version: "7.0.12"
app:
  cors:
    mappingPathPattern: "/**"
    allowed-origins: ${ALLOWED_SOURCES}
    allowed-methods: [ GET, POST, PUT, DELETE, PATCH ]
    allowed-headers: [ "*" ]
