spring:
  application:
    name: recipe-book-spring
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: "mongodb://localhost:27017/test"
  datasource:
    driver-class-name: "com.dbschema.MongoJdbcDriver"
    url: "jdbc:mongodb://localhost:27017/test"
  flyway:
    sql-migration-suffixes: [ ".js" ]
de:
  flapdoodle:
    mongodb:
      embedded:
        version: "7.0.12"
app:
  cors:
    mappingPathPattern: "/**"
    allowed-origins: ${ALLOWED_SOURCES}
    allowed-methods: [ GET, POST, PUT, DELETE, PATCH ]
    allowed-headers: [ "*" ]
  key-pair:
    private-key: ${PRIVATE_KEY}
    public-key: ${PUBLIC_KEY}
server:
  error:
    include-stacktrace: never