app:
  cors:
    mappingPathPattern: "/**"
    allowed-origins: [ "*" ]
    allowed-methods: [ "*" ]
    allowed-headers: [ "*" ]
logging:
  level:
    org:
      springframework:
        security: DEBUG
