###
POST http://localhost:8080/auth/generateToken
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

> {%
    client.global.set("auth_token", response.body);
%}

###

###
POST http://localhost:8080/auth/createUser
Content-Type: application/json

{
  "username": "user@mail.com",
  "password": "password"
}

###

PUT http://localhost:8080/recipes/batch
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[
  {
    "name": "Delicious Pizza",
    "description": "A slice of pizza topped with gooey cheese and savory toppings, perfect for any occasion.",
    "imagePath": "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "ingredients": [
      {
        "name": "Pizza dough",
        "amount": 1
      },
      {
        "name": "Tomato sauce",
        "amount": 2
      },
      {
        "name": "Mozzarella cheese",
        "amount": 4
      }
    ]
  },
  {
    "name": "Juicy Hamburger",
    "description": "A perfectly grilled hamburger patty, bursting with flavor and topped with fresh ingredients.",
    "imagePath": "https://images.unsplash.com/photo-1602192103201-d763907bc41b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D/photo-1513104890138-7c749659a591",
    "ingredients": [
      {
        "name": "Ground beef",
        "amount": 3
      },
      {
        "name": "Hamburger buns",
        "amount": 6
      },
      {
        "name": "Fresh lettuce",
        "amount": 1
      }
    ]
  },
  {
    "name": "Healthy Salad",
    "description": "A refreshing mix of crisp vegetables and vibrant greens, tossed in a light, zesty dressing.",
    "imagePath": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D/photo-1513104890138-7c749659a591",
    "ingredients": [
      {
        "name": "Mixed greens",
        "amount": 2
      },
      {
        "name": "Cherry tomatoes",
        "amount": 10
      },
      {
        "name": "Light vinaigrette",
        "amount": 1
      }
    ]
  }
]

###
POST http://localhost:8080/recipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Delicious Pizza",
  "description": "A slice of pizza topped with gooey cheese and savory toppings, perfect for any occasion.",
  "imagePath": "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "ingredients": [
    {
      "name": "Pizza dough",
      "amount": 1
    },
    {
      "name": "Tomato sauce",
      "amount": 2
    },
    {
      "name": "Mozzarella cheese",
      "amount": 4
    }
  ]
}

###
### GET request to example server
GET http://localhost:8080/recipes
Authorization: Bearer {{auth_token}}

###